version: "3.9"

services:
  localledger:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: localledger-app
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
